spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jooroot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update   # 개발할 땐 update, 운영은 validate 권장
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: wndudwnswndudwnswndudwnswndudwnswndudwns
  token-validity: 3600000
